from pydantic import BaseModel, Field



class StrategyAgentOutput(BaseModel):

    strategy: str = Field(..., description="The strategy elaborated by the Strategy Agent")



class SoftwareAgentOutput(BaseModel):

    code: str = Field(..., description="The code to be executed generated by the SoftwareAgent")

class ErrorAgentOutput(BaseModel):

    intent: str
    message: str

class LoggerAgentOutput(BaseModel):

    intent: str
    message: str

class ClassificationAgentOutput(BaseModel):

    user_query: str
    reformulated_query: str
    classification: str

class RephraseOutput(BaseModel):

    user_query: str
    reformulated_query: str

class ExtractKeywordOutput(BaseModel):
    keyword: list[str]

class NoCodingAgentOutput(BaseModel):
    intent: str
    message: str